mappings:
  QueuedJobsAdmin: SilverStripe\QueuedJobs\Controllers\QueuedJobsAdmin
  QueuedJobDescriptor: SilverStripe\QueuedJobs\DataObjects\QueuedJobDescriptor
  QueuedJobRule: SilverStripe\QueuedJobs\DataObjects\QueuedJobRule
  ScheduledExecutionExtension: SilverStripe\QueuedJobs\Extensions\ScheduledExecutionExtension
  GridFieldQueuedJobExecute: SilverStripe\QueuedJobs\Forms\GridFieldQueuedJobExecute
  CleanupJob: SilverStripe\QueuedJobs\Jobs\CleanupJob
  DeleteObjectJob: SilverStripe\QueuedJobs\Jobs\DeleteObjectJob
  DoormanProcessManager: SilverStripe\QueuedJobs\Jobs\DoormanProcessManager
  DoormanQueuedJobTask: SilverStripe\QueuedJobs\Jobs\DoormanQueuedJobTask
  GenerateGoogleSitemapJob: SilverStripe\QueuedJobs\Jobs\GenerateGoogleSitemapJob
  PublishItemsJob: SilverStripe\QueuedJobs\Jobs\PublishItemsJob
  ScheduledExecutionJob: SilverStripe\QueuedJobs\Jobs\ScheduledExecutionJob
  AbstractQueuedJob: SilverStripe\QueuedJobs\Services\AbstractQueuedJob
  DefaultQueueHandler: SilverStripe\QueuedJobs\Services\DefaultQueueHandler
  GearmanQueueHandler: SilverStripe\QueuedJobs\Services\GearmanQueueHandler
  ImmediateQueueHandler: SilverStripe\QueuedJobs\Services\ImmediateQueueHandler
  QueuedJob: SilverStripe\QueuedJobs\Services\QueuedJob
  QueuedJobService: SilverStripe\QueuedJobs\Services\QueuedJobService
  JobErrorHandler: SilverStripe\QueuedJobs\Services\JobErrorHandler
  BaseRunner: SilverStripe\QueuedJobs\Tasks\Engines\BaseRunner
  DoormanRunner: SilverStripe\QueuedJobs\Tasks\Engines\DoormanRunner
  QueueRunner: SilverStripe\QueuedJobs\Tasks\Engines\QueueRunner
  TaskRunnerEngine: SilverStripe\QueuedJobs\Tasks\Engines\TaskRunnerEngine
  CreateQueuedJobTask: SilverStripe\QueuedJobs\Tasks\CreateQueuedJobTask
  DummyQueuedJob: SilverStripe\QueuedJobs\Tasks\DummyQueuedJob
  ProcessJobQueueChildTask: SilverStripe\QueuedJobs\Tasks\ProcessJobQueueChildTask
  ProcessJobQueueTask: SilverStripe\QueuedJobs\Tasks\ProcessJobQueueTask
  PublishItemsTask: SilverStripe\QueuedJobs\Tasks\PublishItemsTask
  JobWorker: SilverStripe\QueuedJobs\Workers\JobWorker
  QJUtils: SilverStripe\QueuedJobs\QJUtils
